name: React Testing

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: node --version
      - run: npm ci
      - run: npm run build --if-present

      - name: Deploy to VPS
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr
          path: dist/
          remote_path: /var/www/junglezone-cicdtest2/
          remote_host: 20.197.33.168
          remote_port: 22
          remote_user: qubicle
          remote_key: ${{ secrets.DEPLOY_KEY }}
